### ISSUE TITLE
Would like to contribute

### ISSUE THREAD

**Issue by Josanshuo** [DomDumont/CartaGen#3]
This tool looks great, and I would like to help the migration. Wondering how could I involve into it?

**Comment by DomDumont** [comment]
Hi, migration to what ? What idea do you have in mind ? For me this project is over but I am open to new ideas.

**Comment by Josanshuo** [comment]
Thanks for the quick response.

I was assuming this Github repo is a migration from old bitbucket project based on #2 and almost empty code. I used the tool and feel it is really powerful. However, when I want to export the cards, it only can print to PDF. So I would like to add the following features based on my use case:

1. export individule card
2. set sheet size to fit more images (in order to support TTS 10x7 custom deck)
3. adjust transparent for images

**Comment by DomDumont** [comment]
Hi Josan,
This is a very old project of mine. I thought the source code was here but if you tell me the code is empty, I may have to search a little bit to find it. You may be right, it might have been a bitbucket project. You're not the only one to find it useful. A guy even pay for this alpha on itchio ! Let me dig a little bit to find the source code. I will get back to you

**Comment by Josanshuo** [comment]
Thank you! I think there is no competitors in the market for WYSIWYG playing card design, except Adobe Photoshop, GIMP, and etc, which are over complicated and pricey.  This tool is niche for testing, TTS, and fan-made content, because it is focus and easy to use. I also willing to pay for it if the feature and price is decent. :)

**Comment by Josanshuo** [comment]
BTW, another reason I knew this repo is in progress of migration is from the todo Kanban card: https://github.com/DomDumont/CartaGen/projects/1#card-2787938

**Comment by DomDumont** [comment]
Hi, I found the sources on bitbucket. Unfortunately I cannot update this repo for many reasons : 
1) the code is very old, awful and really not ready for prime time
2) the code contains some personal libraries that I cannot open source yet
That's why I wanted originally to recreate this new repo from scratch instead of just copy my bitbucket repo here.

So I will need some extra time ...

BUT,  I understand you want some extra features and I already tried to add some of them : 

- export individual card
- set sheet size to fit more images (in order to support TTS 10x7 custom deck)

I just uploaded a new version 0.3.0 on itch.io, please take some time to try it and tell me how it goes.  Do not hesitate to report bugs.
I changed Qt5 to Qt6 and it may add some instability on an already very unstable software ;-)

Thanks for your patience

https://domdumont.itch.io/cartagen/devlog/500521/cartagen-030

**Comment by Josanshuo** [comment]
Wow, thanks for the quick release! 

After a quick trail, the export function is fantastic! Really like it, so I could generate a single card to have a quick test in TTS mods.

But I didn't find a way to set the sheet size. I also add more than 8 cards in a sheet, it only show 8 cards.

![image](https://user-images.githubusercontent.com/42686700/224450143-ab394131-94c9-4651-a5d9-eb468d92f9ac.png)

Moreover, I could see the following message in the startup terminal, not sure if it is the cause that sheet option not displayed:
```
qt.core.qobject.connect: QObject::connect: No such signal QComboBox::currentIndexChanged(QString)
QFont::fromString: Invalid description ',9,-1,5,50,0,0,0,0,0'
Cannot retrieve font from settings
Unable to set stylesheet, file not found
```

**Comment by DomDumont** [comment]
my idea was to have only A4 paper size sheets. In my head, sheets were only used to be printed so for example you cannot add more than 8 cards in one sheet because this will not fit in an A4 paper. If you want sheets of any arbitrary size, it's another features, please create an new issue for this and explain to me how you plan to use those sheets. Thanks
